export const GET_LATEST_UPTIME = "GET_LATEST_UPTIME";
export const RECEIVED_LATEST_UPTIME = "RECEIVED_LATEST_UPTIME";
export const GET_COMPONENTS_COUNT = "GET_COMPONENTS_COUNT";
export const RECEIVED_COMPONENTS_COUNT = "RECEIVED_COMPONENTS_COUNT";
export const GET_ENTITIES_COUNT = "GET_ENTITIES_COUNT";
export const RECEIVED_ENTITIES_COUNT = "RECEIVED_ENTITIES_COUNT";
export const GET_ENTITIES_TRANSACTION_COUNTS = "GET_ENTITIES_TRANSACTION_COUNTS";
export const RECEIVED_ENTITIES_TRANSACTION_COUNTS = "RECEIVED_ENTITIES_TRANSACTION_COUNTS";
export const GET_COMPONENTS_TRANSACTION_COUNTS = "GET_COMPONENTS_TRANSACTION_COUNTS";
export const RECEIVED_COMPONENTS_TRANSACTION_COUNTS = "RECEIVED_COMPONENTS_TRANSACTION_COUNTS";
export const GET_WEEKLY_TRANSACTION_COUNTS = "GET_WEEKLY_TRANSACTION_COUNTS";
export const RECEIVED_WEEKLY_TRANSACTION_COUNTS = "RECEIVED_WEEKLY_TRANSACTION_COUNTS";
export const GET_LOGS = "GET_LOGS";
export const RECEIVED_LOGS = "RECEIVED_LOGS";

export const ADD_COMPONENT = "ADD_COMPONENT";
export const REMOVE_COMPONENT = "REMOVE_COMPONENT";
export const EDIT_COMPONENT = "EDIT_COMPONENT";

export const ADDED_COMPONENT = "ADDED_COMPONENT";
export const REMOVED_COMPONENT = "REMOVED_COMPONENT";
export const EDITED_COMPONENT = "EDITED_COMPONENT";

export const SHOW_COMPONENT_WINDOW = "SHOW_EDIT_COMPONENT_WINDOW";
export const SHOW_ENTITY_WINDOW = "SHOW_ENTITY_WINDOW";
