export const GET_LATEST_UPTIME = "GET_LATEST_UPTIME";
export const RECEIVED_LATEST_UPTIME = "RECEIVED_LATEST_UPTIME";
export const GET_COMPONENTS_COUNT = "GET_COMPONENTS_COUNT";
export const RECEIVED_COMPONENTS_COUNT = "RECEIVED_COMPONENTS_COUNT";
export const GET_ENTITIES_COUNT = "GET_ENTITIES_COUNT";
export const RECEIVED_ENTITIES_COUNT = "RECEIVED_ENTITIES_COUNT";